name: Distro windows

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout pymontecarlo
        uses: actions/checkout@v2
        with:
          path: pymontecarlo
          fetch-depth: 0
          lfs: true
      - name: Checkout pymontecarlo-gui
        uses: actions/checkout@v2
        with:
          repository: pymontecarlo/pymontecarlo-gui
          path: pymontecarlo-gui
          fetch-depth: 0
          lfs: true
      - name: Checkout pymontecarlo-casino2
        uses: actions/checkout@v2
        with:
          repository: pymontecarlo/pymontecarlo-casino2
          path: pymontecarlo-casino2
          fetch-depth: 0
          lfs: true
      - name: Checkout pymontecarlo-penepma
        uses: actions/checkout@v2
        with:
          repository: pymontecarlo/pymontecarlo-penepma
          path: pymontecarlo-penepma
          fetch-depth: 0
          lfs: true
      - name: Checkout pypenelopetools
        uses: actions/checkout@v2
        with:
          repository: pymontecarlo/pypenelopetools
          path: pypenelopetools
          fetch-depth: 0
          lfs: true
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip codecov setuptools wheel
          pip install --upgrade -r pymontecarlo/distros/windows/requirements.txt
      - name: Create distro
        run: |
          mkdir dist
          python pymontecarlo/distros/windows/create.py --debug -d dist
          dir dist
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pymontecarlo-distro-windows
          path: dist/*.zip
