name: Distro windows

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout pymontecarlo
        uses: actions/checkout@v2
        with:
          path: pymontecarlo
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip codecov setuptools wheel
          pip install --upgrade -r pymontecarlo/distros/windows/requirements.txt
      - name: Create distro
        run: |
          mkdir dist
          python pymontecarlo/distros/windows/create.py --pypi -d dist
          dir dist
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pymontecarlo-distro-windows
          path: dist/*.zip
